import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import theme from "../theme.ts";

export const metadata: Metadata = {
  title: "DHS Bell Schedule",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body>
            <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
            {children}
            </ThemeProvider>
            </AppRouterCacheProvider>
            </body>
        </html>
    );
}
