CREATE TABLE analytics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    value INTEGER NOT NULL DEFAULT 0,
    UNIQUE (name, date)
);