export enum Period {
    PERIOD_EB = 0,
    PERIOD_1 = 1,
    PERIOD_2 = 2,
    PERIOD_3 = 3,
    PERIOD_4A = 4,
    PERIOD_4B = 5,
    PERIOD_5A = 6,
    PERIOD_5B = 7,
    PERIOD_6A = 8,
    PERIOD_6B = 9,
    PERIOD_7 = 10,
    PERIOD_8 = 11,
    PERIOD_HR = 12,
    PERIOD_STAFF_COLLABORATION = 13,
    PERIOD_LUNCH_1 = 14,
    PERIOD_LUNCH_2 = 15,
    PERIOD_LUNCH_3 = 16,
    PERIOD_LUNCH_A = 17,
    PERIOD_LUNCH_B = 18,
    PERIOD_LUNCH_C = 19,
}