name: Deploy Next.js site to Pages
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install root dependencies (for husky)
        run: npm ci
      - name: Install client dependencies
        run: npm ci
        working-directory: packages/client
      - name: Build with Next.js
        run: NODE_ENV=production npx --no-install next build
        working-directory: packages/client
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/client/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
